### ISSUE TITLE
Cookies cleared on app restart in Android release build

### ISSUE THREAD

**Issue by logidelic** [manifoldjs/ManifoldCordova#100]
We have developed an app using ManifoldCordova to load an external website (controlled by us) as the main UI.

Everything works fine in iOS and also in the Android Debug build. However, when we make an Android Release build, cookies are reset (cleared) when the app is restarted. Have others experienced this as well?

**Comment by boyofgreen** [comment]
haven't seen this, but I noticed it was closed.  Were you able to solve?

**Comment by logidelic** [comment]
I closed because I discovered that this was reproducible on some devices but not others... Until I have further info I'm assuming that this is not a bug in ManifoldCordova, but I will surely re-open if I convince myself otherwise. :)

**Comment by boyofgreen** [comment]
sounds good :)
