### ISSUE TITLE
Is there a soon coming update?

### ISSUE THREAD

**Issue by tonejac** [manifoldjs/ManifoldCordova#105]
Will ManifoldCordova be updated to work with:
- cordova-android: 6.2.3
- cordova-ios: 4.5.0

I'm getting the "Plugin doesn't support this project's [platform] version" message when attempting to install.

**Comment by flatirontek** [comment]
+1

**Comment by fnicollet** [comment]
Not really helpful but I have the same issue during install:
```

**Comment by fnicollet** [comment]
Not really helpful but I have the same issue during install
```
Installing "cordova-plugin-hostedwebapp" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: <=5.1.9
```

Is there a reason why there is a restriction on the cordova version in the first place?

Thanks,
Fabien

**Comment by boyofgreen** [comment]
Hi Folks, we have ran into a number of compatibility issues in the past with upgrades, so we've frozen the version to the top version we've tested.  You can alter the supported version number with a fork of it, and I wouldn't expect any problems.

**Comment by fnicollet** [comment]
Hello @boyofgreen and thanks for responding. 

Could do a fork, but that's a bit annoying to prepare (and some other users probably can't just fork it, with projects which will only pull plugins from the cordova repository). Currently, the plugin cannot be installed out-of-the-box, I believe a version could be released to fix the patches have already been applied to the sources. Also, there is a PR which has never been merged which seems important.

On a side note, is this project abandonned? It looks like all the maintainers (from Microsoft) left the project more than a year ago? 
I would totally understand if that's the case, it's just an interesting to know if the project is dead or not for people who would like to use it. Might be good to add it at the top of the README.md as well, to avoid surprises.

Fabien

**Comment by rschrenk** [comment]
Its now half a year that this question has been asked - I fear this project is dead although it was very promising for web development....

**Comment by boyofgreen** [comment]
Hi folks, just FYI, as we don't have a new iOS platform yet, we are going to do one more additional release to manifold-cordova to bring it up to the most recent version of cordova. look for that in the next few weeks.  merging PRs this week
