### ISSUE TITLE
Error: Cannot find module '../../node_modules/elementtree'

### ISSUE THREAD

**Issue by cdcv** [manifoldjs/ManifoldCordova#106]
Not sure if this is the same issue as a previous one related to this.  That issue was closed, but the issue seems to remain.
I just followed the instructions for building an example app.  Btw, it would be great to provide an actual example, with a working manifest file, so people could be sure that everything is right.  The error seems to be present when building for either ios or android.
I followed the install script from the readme, so presumably the most recent version of the plugin.

I'm running this on:
Mac OS 10.12.6
Node 8.9.1
NPM 5.5.1
Cordova 8.0.0
cordova-ios@~4.5.4
cordova-android@7.0.0

Thanks for your help!

Here is the command-line output.
cordova build

Updating Cordova configuration from W3C manifest...
The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
(node:6212) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../../node_modules/elementtree'
(node:6212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
➜  sampleapp cordova emulate android
Updating Cordova configuration from W3C manifest...
The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
(node:6281) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../../node_modules/elementtree'
(node:6281) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

cordova platform add ios    
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: yourdomain.sampleapp
	Name: SampleHostedApp
iOS project created with cordova-ios@4.5.4
Installing "cordova-plugin-hostedwebapp" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.4, failed version requirement: <=4.1.9
Skipping 'cordova-plugin-hostedwebapp' for ios
Updating Cordova configuration from W3C manifest...
The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
(node:7092) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../../node_modules/elementtree'
(node:7092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sunsus** [comment]
Any update on this Issue

**Comment by mattwoberts** [comment]
* ping *

Hey @boyofgreen sorry to keep badgering you here, but I'm worried that this issue, and other issues related to getting the app working on IOS, are being ignored.

Currently, only an older version of cordova-ios is supported (<=4.1.9), and there are issues like this one that are being reported but aren't being worked on.

What would be great, is an update re: where we are with this plugin. With the PWABuilder reboot, are we still being encouraged to wrap our PWAs in cordova (it's an essential for us really, we need the users, and the users are in the app stores). If this aspect of the PWAbuilder is being retired, are we best served by looking at other ways to host our PWAs in cordova - doing it manually without `cordova-plugin-hostedwebapp` maybe?

Anyhoo, any update on where we're all would be awesome :)

**Comment by boyofgreen** [comment]
Hi Matt,
  So right now we don't have anyone on the project who has the Cordova experience.  I would absolutely be open to pull requests though.  For Android, we are moving away from Cordova to a different approach, but we are still using Cordova for iOS at this point.  I'll ask our current team to see if anyone can take a look, but we are on the search for some Cordova skills to help.
Thanks,
Jeff

**Comment by mattwoberts** [comment]
Thanks @boyofgreen. There's a specific fix that addresses this "elementtree" bug, that's been closed in https://github.com/pwa-builder/ManifoldCordova/issues/82 but I think it just needs bringing in.

I wish I had core cordova / ios skills that I could contribute, but alas!

Could you tell me a little more about the android approach you're moving to?

Thanks

Matt

**Comment by boyofgreen** [comment]
yep, it is going to look pretty much like this:
https://github.com/pwa-builder/pwabuilder-android
The idea is to make the wrapper as slim as possible.  We loose the Cordova API access, but we the folks at the chrome team and I agree this is a better direction.

**Comment by pauloya** [comment]
We're getting the ConfigParser error when building cordova-android for latest versions.
Does anyone know of similar plugins that support the hostedwebapps approach?

**Comment by boyofgreen** [comment]
Hi folks, considering we don't have a full solution for iOS yet, we are doing one more update to the manifold-cordova platform to bring it up to the most recent versions of cordova.  Happy to pass it on if anyone wants to take ownership of it after that.  PRs are being taken in this week, and should be on the website in a few weeks.
