### ISSUE TITLE
Add support for the "hardware" back button in Windows Phone

### ISSUE THREAD

**Issue by ghost** [manifoldjs/ManifoldCordova#13]
When pressing the back button, the app is closed instead of navigating to the previous page in the webview stack, similar to what cordova app for Android does.

Currently, this feature is present in the [Web-App-ToolKit plugin](https://github.com/boyofgreen/Web-App-ToolKit). We should consider to move this feature to the ManifoldCordova plugin.

**Comment by f2bo** [comment]
Hardware back button now navigates the webview history (see https://github.com/manifoldjs/ManifoldCordova/commit/ed333c547b2741993d242cd092fc0df2e0a37e2c).
