### ISSUE TITLE
Change Plugin Name

### ISSUE THREAD

**Issue by axemclion** [manifoldjs/ManifoldCordova#36]
The repo for this plugin is called Manifold Cordova, and the plugin itself is called `cordova-plugin-hostedwebapp`. This plugin is pretty useful for a general cordova app to detect network issues and display an offline page. 
Please consider re-naming this plugin to `cordova-plugin-offlinepage` to better reflect its purpose.

**Comment by f2bo** [comment]
While the plugin is capable of detecting network connectivity changes and showing an offline page, as I explained in your other issue (https://github.com/manifoldjs/ManifoldCordova/issues/35), its main purpose is to create hosted web apps. 

If you only need to show an offline page, then using the standard network-information plugin might be enough.

**Comment by axemclion** [comment]
The network status plugin alone cannot display a page, especially when using in a Cordova hosted app created using the CLI. 

The plugin uses a second webview, and has native code to display the offline page - if I wanted as similar functionality, i would simply end up rewriting this plugin. 

cc @boyofgreen
