### ISSUE TITLE
Icons from manifest - wrong name in config.xml

### ISSUE THREAD

**Issue by mattwoberts** [manifoldjs/ManifoldCordova#57]
I think this is a bug, although there is a chance it's me misunderstanding something:

1) Create a manifest, and add a bunch of icons, for example:

```
    "icons": [
        {
            "src": "/content/images/mobile/icons/mdpi/harry.png",
            "sizes": "48x48",
            "type": "image/png"
        },
        {
            "src": "/content/images/mobile/icons/hdpi/harry.png",
            "sizes": "72x72",
            "type": "image/png"
        },
        {
            "src": "/content/images/mobile/icons/xhdpi/harry.png",
            "sizes": "96x96",
            "type": "image/png"
        },
        {
            "src": "/content/images/mobile/icons/xxhdpi/harry.png",
            "sizes": "144x144",
            "type": "image/png"
        }
    ],   
```

Notice how the name is harry.png.

Now, when you do a `cordova prepare`, the icons are downloaded and copied into the cordova folder into the correct paths, BUT when they get copied to the android res folder, they are all renamed to icon.png, which is at odds with the manifest and config.xml.

When you then run the resulting app (for me, on an android device), you don't see the specified icon, just the manifold logo. I'm assuming this is because it looked for, and failed to find harry.png?

**Comment by nikolowry** [comment]
Is there a reason why we can't specify in the manifest to use local image assets as opposed to remote ones?

I get that we can always use the config.xml, but was curious as to why the option isn't more flexible in Manifoldjs?

**Comment by mattwoberts** [comment]
Could someone confirm if this is a bug or a misunderstanding on my part?

**Comment by mattwoberts** [comment]
Ah - right, this is mostly my bad...

It turns out that cordova controls the naming of the icons in the project, you have little control over it, so the fact that they are called `icong.png` is not an issue.

I was getting confused because my icons weren't being used - but this is because I didn't specify a ldpi icon, and the manifold one was being used instead.

**Comment by boyofgreen** [comment]
Is there anything we can do to make this more natural?
