### ISSUE TITLE
Cordova iOS 4.x support

### ISSUE THREAD

**Issue by giovannidegani** [manifoldjs/ManifoldCordova#58]
Is there any plans to support cordova ios 4.x ? What are the issues preventing this to work ?

**Comment by boyofgreen** [comment]
Nothing really, you can upgrade your local copy to 4.x.  We originally just always used the latest version of cordova, but then we got burnt a few times with building dependences on something, then having it change from under us, so for stability we manually upgrade.

**Comment by giovannidegani** [comment]
Thanks, but I'm getting errors trying to run on ios 4.0.1
The plugin does not build due to errors in CDVHostedWebApp.m when trying to set the webview delegate in pluginInitialize method. I think it is because in cordova 4.x we can choose the webview engine to be either UIWebView or WKWebView and this added some abstraction on the engine in the plugin SDK. I'm tryng to find out how to fix it.
