### ISSUE TITLE
cordova.plugins not available in webview?

### ISSUE THREAD

**Issue by gabn88** [manifoldjs/ManifoldCordova#60]
Hi and thanks for this nice plugin.

I have setup the plugin according to the tutorial.
I also included some plugins, for example the ionic-keyboard-plugin.
Now when I chrome://inspect on my device, cordova.plugins does not exist. It seems like the page is loaded without the plugins?

My manifest:

{
  "lang": "en",
  "name": "rd",
  "short_name": "rd",
  "icons": [{
        "src": "icon/lowres",
        "sizes": "64x64",
        "type": "image/webp"
      }, {
        "src": "icon/hd_small",
        "sizes": "64x64"
      }, {
        "src": "icon/hd_hi",
        "sizes": "128x128",
        "density": 2
      }],
  "scope": "/",
  "start_url": "https://linkedin.com",
  "display": "fullscreen",
  "orientation": "landscape",
  "theme_color": "aliceblue",
  "mjs_api_access": { "match": "*", "platform": "android", "access": "cordova" }
}

The offline event works well!

**Comment by gabn88** [comment]
nevermind, now it works.

**Comment by boyofgreen** [comment]
great, how did you get it working?  Would be good to include for others.
Thanks,
Jeff

**Comment by gabn88** [comment]
To be honoust, I don't know what it was. 

What I do know is that if you have some Javascript heavy pages, it looses the cordova object on the page with the following log:

```
Could not find cordova.js script tag. Plugin loading may fail.
hostedapp-bridge.js:1187 deviceready has not fired after 5 seconds.
hostedapp-bridge.js:1180 Channel not fired: onPluginsReady
hostedapp-bridge.js:1180 Channel not fired: onCordovaReady
```

**Comment by gabn88** [comment]
Maybe it would be a good idea to load the cordova script first (if possible)?
