### ISSUE TITLE
ios - !gap_exec requests

### ISSUE THREAD

**Issue by mattwoberts** [manifoldjs/ManifoldCordova#63]
I'm injecting a javascript file to do some mobile-specific things like set up notifications etc...

I just noticed that I'm getting loads of HEAD requests to my wrapped site, for the URL `https://mywrappedsite.com/!gap_exec`

Now, as far as I can tell, this isn't affecting the app - everything seems to be running OK, but I'm still seeing a bunch of these requests for each page load. Even if I comment out the injected script so that it doesn't do anything, I'm still seeing one hit per request.

Soooooo, it would appear that `gap_exec` is something that cordova uses internally to talk to internal phone hardware, correct? (Source: http://stackoverflow.com/questions/16631230/phonegap-cordova-2-7-0-exec-gap-file-not-found)

So it looks like something is ammis here? I can see on the ios specific cordova.js, line 1016:

`execXhr.open('HEAD', "/!gap_exec?" + (+new Date()), true);`

Now, because that url is relative - / rather than file:// I can see why this potentially might upset things for a hosted web app.

Thoughts?

**Comment by mircoc** [comment]
Hello,
i had an issue on my app with failing ajax calls, because of too much of these HEAD requests, the browser was blocking my ajax call.

So i changed the cordova communication type to iframe_nav:

``` javascript
var exec = cordova.require('cordova/exec');
exec.setJsToNativeBridgeMode(exec.jsToNativeModes.IFRAME_NAV);
```

The bridge mode is set by hostedwebapp when it inject cordova in a page:
https://github.com/manifoldjs/ManifoldCordova/blob/master/www/hostedapp-bridge.js#L45

**Comment by mattwoberts** [comment]
Thanks for that @mircoc, that's really helpful.

So is this something that we should change - do we need to create a pull request with this change? I'm not sure what the implications will be switching it to IFRAME_NAV - are there other things to be aware of? Does setting it to IFRAME_NAV stop it from making these HEAD requests?

It seems a bit weird to me that we're making all these eroneous requests, and something we should get sorted out in this project?

Cheers

**Comment by boyofgreen** [comment]
Thanks @mircoc  and @mattwoberts  as always :)  We are going to start another release after build and we'll look at this.  I'm not the cordova Expert so I don't know what the tradeoff is, but we'll research.  Any other feedback is helpful.

**Comment by mattwoberts** [comment]
I'll be very keen to see what happens with this.

The consensus on a little googling is that IFRAME_NAV is a little faster and should get round this problem, but it might (or might not, depending on what jira issues you read) have issues of it's own: 

https://github.com/LonnyGomes/cordova-ios/blob/master/guides/Changing%20the%20JavaScript%20to%20Native%20Bridge%20Mode.md

I'm not going to switch to IFRAME_NAV for now, I'm wondering if I should just create a route for that URL on the server to at least stop it from cluttering up my logs.

**Comment by boyofgreen** [comment]
we'll start with some research on this.
