### ISSUE TITLE
Android: evaluateJavascript fallback fails

### ISSUE THREAD

**Issue by phoboslab** [manifoldjs/ManifoldCordova#64]
On devices that don't support the `evaluateJavascript` method on the WebView, the fallback using `.loadUrl("javascript:" + ...)` doesn't properly work either.

```
E/Web Console: Uncaught SyntaxError: Unexpected token % at null:1
```

All special chars of the script are "percent encoded" by `Uri.encode()` before being handed over to `.loadUrl()`, which seems to cause this error. I.e. it will choke on spaces in the script (`%20`) and such.

Simply removing the `Uri.encode()` call seems to fix the problem:
https://github.com/manifoldjs/ManifoldCordova/blob/master/src/android/HostedWebApp.java#L550

```
me.webView.getEngine().loadUrl("javascript:" + scriptToInject, false);
```

Tested on Android Jelly Bean 4.3, Samsung Galaxy Nexus

**Comment by boyofgreen** [comment]
Thanks @phoboslab we have a new release we are starting in a few weeks that will be mostly bug fixes, we'll add this in!
