### ISSUE TITLE
ManifoldCordova freeze (Android) app

### ISSUE THREAD

**Issue by gabn88** [manifoldjs/ManifoldCordova#65]
On my external page i have some javascript code that creates an event.

This event is caught by some javascript within my app.

Sometimes the app freezes completely.
## It also raises the error below several times when reloading the page (not sure if this is related):

// Workaround for Windows 10 in hosted environment case
// http://www.w3.org/html/wg/drafts/html/master/browsers.html#named-access-on-the-window-object
if (window.cordova && !(window.cordova instanceof HTMLElement)) {
    throw new Error("cordova already defined");
}

**Comment by gabn88** [comment]
Ah, I found the line that creates the error: 
    history.pushState('', document.title, window.location.pathname);

**Comment by boyofgreen** [comment]
HI @gabn88 so lineing up work for next version.   Looks like you found your error and are working now?

**Comment by gabn88** [comment]
It is working now! However, I still wasn't able to fully reproduce the freeze and solve it. We have around 20 systems that work 24/7 and two of them freezed, even when rebooting the went into the freeze and recovered only after disabling the wifi, which meant a connection was lost. However I'm not even sure if it is related to manifoldjs, so I'll close this ticket.
