### ISSUE TITLE
Update Cordova?

### ISSUE THREAD

**Issue by jsmylnycky** [manifoldjs/ManifoldCordova#66]
I'm running the latest version of Cordova, which means I get deprecation warnings because this plugin requires very outdated versions of iOS and Android.

```
Installing "cordova-plugin-hostedwebapp" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 5.1.1, failed version requirement: <=4.1.1
Skipping 'cordova-plugin-hostedwebapp' for android
Installing "cordova-plugin-hostedwebapp" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.1.1, failed version requirement: <=3.9.2
Skipping 'cordova-plugin-hostedwebapp' for ios

```

Any chance of getting this updated anytime soon?

**Comment by colinfindlay-nz** [comment]
Also wondering the same thing. Tried my own manual update and it broken horribly on iOS, this is likely due to me not having much of a clue just yet.

**Comment by boyofgreen** [comment]
Yes, we have an update planned in a few weeks.  We originally allowed the plugin to work with any version, but we got stuck with a few compat issues, so we backed off of the edge versions.  Adding @f2bo for awareness.

**Comment by jasonshortphd** [comment]
What version of Cordova are you trying to use?  

I am testing using the 5.x, but since that doesn't exist for ios yet it resolves it to current 4.1.1.  Is this the same thing you guys are seeing?

**Comment by jsmylnycky** [comment]
@jasonshortphd  4.1.1, as it's noted in my original post... :)

**Comment by colinfindlay-nz** [comment]
@jasonshortphd I feel bad asking about timeframes, but do you have any? I've just noticed that the restriction on having `cordova-ios` 3.9.2 excludes the use of `phonegap-plugin-push` which is fundamental to my current project 😢

**Comment by jasonshortphd** [comment]
I have submitted the changes to the owner, he just has to accept them. :)  I tested on my Mac and everything worked fine, would love to get some feedback once it is merged.

**Comment by boyofgreen** [comment]
Hi @silver2k   sorry about the delay, we are going to pull the remaining issue out of this release so we can move forward with the new version.  We should have it in testing early next week, which I can share with you

**Comment by colinfindlay-nz** [comment]
Thanks for the update guys. I'm currently using the code in the fork  `khino999/ManifoldCordova` with great success - however the sooner I can get back to a proper release the better I'll feel 😃
