### ISSUE TITLE
[Feature] Catch non-200 HTTP responses and try to reload page (in 1 minute?)

### ISSUE THREAD

**Issue by gabn88** [manifoldjs/ManifoldCordova#67]
I have deployed the manifoldjs to some installations now and it is working fine!

However, for my project it would be really helpfull if the manifold shell could detect if a page change was correct, a.k.:

```
first, you are on page /test
then you reload page with (location.reload()), but the server has an issue and gives back 500,
* then the script waits 1 or 5 minutes, and retries to load page again. *
The same for other non-200 responses.
```

**Comment by gabn88** [comment]
Can anyone point me if I'm on the right track?

In handleNetworkConnectionChange in cordova-plugin-hostedwebapp\src\android\HostedWebApp.java change

```
  if (this.isConnectionError) {
    this.activity.runOnUiThread(new Runnable() {
        @Override
        public void run() {
            String currentUrl = me.webView.getUrl();
            me.webView.loadUrlIntoView(currentUrl, false);
        }
    });
```

to:

```
  if (this.isConnectionError) {
    this.activity.runOnUiThread(new Runnable() {
        // try reload the start page every 5 minutes
       }
    }); 
```

( I only need Android)

**Comment by boyofgreen** [comment]
Thanks for the post!  If I understand correctly, you don't want to show the offline page, you just want cancel the navigation and stay on the page until your online?

**Comment by gabn88** [comment]
Thank you @boyofgreen for your response.

First, HTTP 5xx responses do **not** show the offline page. The offline page is for when the device itself is offline (and maybe when a page cannot be reached at all? I should check this to be sure).

Also this issue is not related with the offline page issue/enhancement and for me this issue has higher priority.

The issue is that I have (Android) devices that continually show some webpage. And people using those devices do all kinds of things on that webpage, among which refresh/navigate. But if, at the same moment that they navigate/refresh, I do a server update that fails (I know it should never happen, but...) and my server responses with a HTTP 500 page or maybe a HTTP 502 gateway error or even a HTTP 504 Gateway Timeout, they people are stuck with a page that shows the error.

Because I have hidden the navigation bar, those people have no other option then to restart the device, which is lame. I don't want to show the navigation bar, because I like the extra space on the displays and the navigation bar is also not needed.

By catching the 5xx responses, it would be possible to automatically to retry to load the page, or maybe go to the start_page. (whichever is easier to implement is fine with me) and keep doing this every X minutes untill the page has loaded correctly.

EDIT: Maybe it helps to say that I use the crosswalk plugin. I think it might change the behaviour of the loadUrl function.
