### ISSUE TITLE
Windows 10 UWP Support?

### ISSUE THREAD

**Issue by aaronwjha** [manifoldjs/ManifoldCordova#81]
Does this plugin currently support creating UWP projects for Win10? I noticed in the doc only Windows 8.1 is listed as supported.

**Comment by aaronwjha** [comment]
Bump

**Comment by jasonshortphd** [comment]
The docs say:

visualstudio
(for Windows only) Opens the project file of the generated **Windows 8.1 / Windows 10** app in Visual Studio
package <content-directory> <output-package-path>
**Creates an APPX package for uploading the Windows 10 app to the Store**, where <content-directory> is the folder that contains the app contents, including the appmanifest.xml file and the app's icons, and <output-package-path> is the path to the APPX file to be generated

http://manifoldjs.com/documentation 

But from my own test the app that is generated is actually a Universal Windows 10 App targeting 10.0.10240.0 (so the original release of Windows 10).  You can retarget if you want.  And there is nothing in there that I am aware of that would prevent you from just targeting Windows 8.1 if you wanted.
