### ISSUE TITLE
Cannot find module '../../node_modules/elementtree'

### ISSUE THREAD

**Issue by rmtngh** [manifoldjs/ManifoldCordova#82]
When building for ios, I get this warning:

> The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.

followed by this error:

> Error: Cannot find module '../../node_modules/elementtree'

manifest.json is created before adding plugin and elementtree exists in platforms\ios\cordova\node_modules

**Comment by boyofgreen** [comment]
Thanks for the comment, can you provide us with the os, node version and plugin version you ate using?
Thanks,
Jeff

**Comment by rmtngh** [comment]
Hi Jeff,
I tried on windows 7 & Mac OSX El Capitan,
Windows: 
node -v : 4.3.1
Mac : 
node -v : 6.2.2

---

Plugin version : 0.3.0

I think I found the problem, node_modules is located in  `platforms/ios/cordova/node_modules`, but in js files inside scripts folder of the plugin,  the path is `cordova-lib/node_modules`. I changed `cordova-lib` to `cordova` and build was successful, but not sure yet if the plugin functions well.

Thanks,
Ramtin

**Comment by cometta** [comment]
anyone manage to get this fix? I have this issue for android as well

**Comment by boyofgreen** [comment]
are you using nvm by chance?

**Comment by cometta** [comment]
@boyofgreen , nope i'm not using nvm.  

node -v
v6.3.1
npm -v
3.10.5

**Comment by cometta** [comment]
i found the problem, here is the solution

/project/cordova/plugins/cordova-plugin-hostedwebapp/scripts/updateConfigurationBeforePrepare.js
line 123: change to  context.requireCordovaModule('elementtree');  

/project/cordova/plugins/cordova-plugin-hostedwebapp/scripts/updateConfigurationAfterPrepare.js
line 32: change to context.requireCordovaModule('elementtree');

**Comment by boyofgreen** [comment]
Thank you @cometta we have work starting soon, we'll get this fix in.

**Comment by bobalazek** [comment]
Any updates on this? Still having issues with that. I could fix the issue locally, the build happens in the ionic could, so the local fix doesn't really help. Any ideas?

**Comment by mattwoberts** [comment]
@boyofgreen why has this been closed, the error is still very much live....
