### ISSUE TITLE
Manually loaded vs. automatically loaded

### ISSUE THREAD

**Issue by jasonfutch** [manifoldjs/ManifoldCordova#87]
Is it possible to load the local index.html first and then trigger when I want to load a choosen manifest file?

**Comment by boyofgreen** [comment]
So you can do this , but it will take a bit of work on your end.  Basically, you'll want to generate the apps, then update the start page to point to your internal page.  The the internal page can do a redirect to your web page.  I've done this before when I knew my site took a while to laod, and I wanted to provide somewhat of an "instant" experience for users.
