### ISSUE TITLE
Incompatibility with cordova-plugin-statusbar > 0.1.6

### ISSUE THREAD

**Issue by srgpqt** [manifoldjs/ManifoldCordova#88]
When cordova-plugin-hostedwebapp is used together with cordova-plugin-statusbar, the WebView becomes non-interactive (cannot click on links/buttons/forms) and the scrolling breaks (somehow, scrollbars can appear).

The issue is present for any version of cordova-plugin-statusbar greater than 0.1.6 (older versions will work).

Removing [this last line](https://github.com/manifoldjs/ManifoldCordova/blob/master/src/ios/CDVHostedWebApp.m#L363) from `createOfflineView` in `CDVHostedWebApp.m` seems to solve the issue but there is probably a better fix to be done?

``` objective-c
[self.viewController.view sendSubviewToBack:self.webView];
```

**Comment by boyofgreen** [comment]
Thank you @srgpqt , we'll look at this in our next dev cycle.  A lot of folks use the offline view, so we'll probably want to figure out the root of the issue.  
Thanks,
Jeff
