### ISSUE TITLE
Plugin doesn't support cordova-android 5.2.2

### ISSUE THREAD

**Issue by bintsiful** [manifoldjs/ManifoldCordova#89]
I am trying to use the hosted-webapp on cordova-android 5.2.2.
Could a possible update of the plugin be done to support this.
Thanks
![error-cordova-android-hosted-webapp](https://cloud.githubusercontent.com/assets/4212454/19288267/3c5cf92a-8ffd-11e6-87f7-ef90d04517c9.png)

**Comment by boyofgreen** [comment]
We use to let it be installed on any version, but then we started to run into breaking changes so often we froze it to particular versions (this is tied to it being part of the manifoldjs project and used to generate the apps with a particular version of cordova).  And we periodically go through and test it with the newest versions and bump I up.  We are probably due for another one.
  In the mean time, it should work fine if you just bring it local, update the [plugin.xml](https://github.com/manifoldjs/ManifoldCordova/blob/268a4e5c81ff6b8bde028ea56651372708da90c5/plugin.xml) and it should work just fine.
@msrodri  does this sound correct?

**Comment by bintsiful** [comment]
@boyofgreen  what in the plugin.xml should i update? could u come clear on the topic.
Thanks
