### ISSUE TITLE
Error installing plugin using Visual Studio 2015 and TACO

### ISSUE THREAD

**Issue by aaronwjha** [manifoldjs/ManifoldCordova#90]
I get the following error trying to add the ManifoldCordova plugin to a Cordova project created in VS2015 using TACO:

> Visual Studio was unable to parse plugin.xml. Please ensure plugin.xml exists and contains no errors.

This occurs when trying to add the plugin by ID or by Git URL.

**Comment by boyofgreen** [comment]
Hi @aaronwjha I have opened a bug with VS so get some help fixing this.  Thanks for letting me know.

**Comment by EgoPlacebo** [comment]
same problem on VS 2017. Any word?
