### ISSUE TITLE
iOS App - Opens safari - Incase url redirections from http to https Web URL

### ISSUE THREAD

**Issue by bikashkumars** [manifoldjs/ManifoldCordova#93]
Cordova v5.4 with Test on iOS 8.x and iOS 9.x.

During first launch, the Cordova iOS app is pointing to https://xyz.com/  **(SSL Site)**, then https://xyz.com/ redirects the application to https://otherdomain.com. User is performaing some task at "https://otherdomain.com" and it redirects the app back to (NON SSL site) http://xyz.com/. this time app opens the safari browser with url as "http://xyz.com/". but its configured that "http://xyz.com/" (NON SSL) is redicting the site back to "https://xyz.com/" (SSL).

Following is sample configuration that we are using.
...
   "start_url": "https://www.xyz.com/",
   "scope":  "/", 
   "mjs_extended_scope": [
     { "url": "http://xyz.com/*" },
     { "url": "https://xyz.com/*" },
     { "url": "http://otherdomain.com/*" }
   ]
...

In-case rule is redefined, then app should work, without such issue.
I have checked xCode console, its shows error like "whitelist issue". But all the required urls has been added to config.xml file as well.

please have a look at this issue. We are stuck at this point. 

But manifold is a awesome work guys, i just love it.

**Comment by boyofgreen** [comment]
Thanks for reaching out!  So I think we've seen a version of this before. @jasonshortphd does this look like the probablem we had the other day with the school search app? Can we pass a solution on?  I'll play with it a bit tomorrow as well and see if I can find where the whitelist is tripping up
