### ISSUE TITLE
Webview cache not being used (iOS)

### ISSUE THREAD

**Issue by pauloya** [manifoldjs/ManifoldCordova#96]
I noticed, in iOS, that the initial load after an app kill the site was taking too long to load and then noticed all resources were loaded from the external site not using the cache.
I found this [bug comment](https://issues.apache.org/jira/browse/CB-3071#comment-15404746), which helped.
Adding this to the config.xml, the cache does get used and initial load is much faster:
`<preference name="AppendUserAgent" value="[my_app_name_here]" />`

**Comment by boyofgreen** [comment]
This is interesting.  Does this bug only happen when you are using a custom user agent or does it happen even when your not tryin to change the useragent?

**Comment by pauloya** [comment]
As far as I can tell its the default behaviour for any Cordova app, it might be only on Cordova 6.3.* that's what I'm using.
I created a HelloWorld app with an iframe and it didn't seem to use caching.
From what I understood the cache is indexed with the user agent which has a unique Id appended every time the app starts, this config key replaces the unique Id with a custom string which allows caching to work in different sessions.
Another thing I noticed is that you can't rely on the safari devtools to tell if it was loaded from cache or not, best just to measure loading time with the network throttled.

**Comment by boyofgreen** [comment]
okay, we'll keep our eye on this.   I appreciate you letting us know about it so we can share with others who run into the same issue.  I'm going to close this issue, and watch the cordova one

**Comment by boyofgreen** [comment]
adding it to the next release.  If this is still the default behavior at that point, we will likely want to include it to just make things run faster for everyone
