### ISSUE TITLE
Superfluous injection into child iframes (iOS)

### ISSUE THREAD

**Issue by logidelic** [manifoldjs/ManifoldCordova#97]
I notice that whenever I load a child iframe in my page (which already has cordova.js injected), I get some message about cordova.js already being loaded... Is there a way to prevent Manifold from attempting injection into child frames? I believe it is causing some other issues as well.

**Comment by boyofgreen** [comment]
Hi @logidelic , we'll put this on the pipeline.

**Comment by boyofgreen** [comment]
Hi @logidelic , look at client mode vs server mode:
https://github.com/manifoldjs/ManifoldJS/wiki/Using-Cordova-Plugins-in-Hosted-Web-Apps
