### ISSUE TITLE
Does not work with the latest cordova-ios version

### ISSUE THREAD

**Issue by gajus** [manifoldjs/ManifoldCordova#98]
Getting error:

> Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.3.1, failed version requirement: <=4.1.9
> Skipping 'cordova-plugin-hostedwebapp' for ios

**Comment by gajus** [comment]
Whats the reason for constructing version constrains using minor version?

https://github.com/manifoldjs/ManifoldCordova/blob/268a4e5c81ff6b8bde028ea56651372708da90c5/plugin.xml#L27-L29

Presumably, major version should be enough.

**Comment by gajus** [comment]
@f2bo Is this still maintained or is there an alternative that I am not finding?

**Comment by boyofgreen** [comment]
You are probably lying right, major versions should be fine.  We tan into a lot of compatability changes at the beginning that caused us to limit it to particular trusted versions.

**Comment by gajus** [comment]
@boyofgreen Are you able to release an upgrade or is there someone else I should be chasing?

**Comment by boyofgreen** [comment]
No, it's me :)  I've added it to our current work stream to test and release for the most recent versions:
https://github.com/manifoldjs/ManifoldJS/issues/268
in the mean time, you can override it in your local and get it to work.  Let me know if it has any issues so I can count it as one of our tests :)

**Comment by boyofgreen** [comment]
off the top of my head, I'm pretty sure you only need to update the cordova.xml https://github.com/manifoldjs/ManifoldCordova/blob/master/plugin.xml
