### ISSUE TITLE
Support for WKWebView on iOS

### ISSUE THREAD

**Issue by danzel** [manifoldjs/ManifoldCordova#99]
If you install the wkwebview plugin, this plugin causes an error.
https://github.com/apache/cordova-plugin-wkwebview-engine
WKWebView is required to get good performance out of a webview on iOS.

Reproducing:
Have a working app using this plugin.
`cordova plugin add cordova-plugin-wkwebview-engine`
Run the app again.

Explodes on this line:
https://github.com/manifoldjs/ManifoldCordova/blob/master/src/ios/CDVHostedWebApp.m#L109

**Comment by danzel** [comment]
I've implemented it over here:
https://github.com/danzel/ManifoldCordova
Feel free to take my changes and integrate them, I've broken usage without it though, that probably wants fixing, I just wasn't sure how to make it work nice, and I don't need it for my use.

Notes on the changes:
.h/.m changes:
Mostly just using the WKWebView classes instead of UIWebView ones.
There is a small hack at https://github.com/danzel/ManifoldCordova/blob/master/src/ios/CDVHostedWebApp.m#L254 that I'm not totally sure how best to resolve.

We bundle the wkwebview js part in at https://github.com/danzel/ManifoldCordova/blob/master/src/ios/CDVHostedWebApp.m#L463, it is required for communicating with native. There is a related change in https://github.com/danzel/ManifoldCordova/blob/master/www/hostedapp-bridge.js#L1-L3 to boot it up before we try use cordova. Without this you will get errors about `gap://ready` in the (web)console. (This cost me a lot of time! So I'm glad to share the reason here.)

**Comment by pauloya** [comment]
Thanks for this, we needed something like this as WKWebView is the way to go.
I don't think the hack you mention matters much, because I don't think the method UIWebView:stringByEvaluatingJavaScriptFromString was synchronous anyway, they just added a callback to the WKWebView method, which is probably not needed for this plugin.

**Comment by boyofgreen** [comment]
thanks @pauloya

**Comment by danzel** [comment]
Did this get added to the main codebase somewhere? I don't see it in the branches or a PR.

We should probably keep this open until this functionality exists in ManifoldCordova?

**Comment by NekR** [comment]
Yeah, would be good to know what's going on here with it.

**Comment by pauloya** [comment]
I wonder if anyone has made this work with both UIWebView and WKWebView? I just realized forcing the WKWebView forces a minimum support for iOS 9.
